services:
  python:
    build: "."
    volumes:
      - "./pyproject.toml:/root/pydiode/pyproject.toml"
      - "./README.md:/root/pydiode/README.md"
      - "./freeze:/root/pydiode/freeze/"
      - "./src:/root/pydiode/src/"
      - "./tests:/root/pydiode/tests/"
    command: ["sleep", "infinity"]
    stop_signal: SIGKILL
